server.port=8080
postgres.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:crypto_bot_db}
postgres.username=${POSTGRES_USER:postgres}
postgres.password=${POSTGRES_PASSWORD:postgres}

rabbitmq.host=${RABBITMQ_HOST:localhost}
rabbitmq.port=${RABBITMQ_PORT:5672}
rabbitmq.username=${RABBITMQ_USER:guest}
rabbitmq.password=${RABBITMQ_PASSWORD:guest}

telegram.bot.token=${TELEGRAM_BOT_TOKEN:}
telegram.chat.id=${TELEGRAM_CHAT_ID:}

openroute.api.key=${OPENROUTE_API_KEY:}
